[versions]
java = "17"
springBoot = "3.1.3"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot",  name = "spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
